### ISSUE TITLE
Camera Parameters for AVD Dataset

### ISSUE THREAD

**Issue by GabrielZH** [shuishida/calvin#1]
I tried to contact the authors of AVD for camera parameters but did not get any response. Would you let me know how you obtained the parameters (camera.txt) when experimenting on the dataset, please? Is contacting authors of the AVD paper the only way I can get them?

**Comment by shuishida** [comment]
Thank you for your interest! Yes, contacting the authors would be the best way to obtain them, although if they do not respond then please reach out and I would be able to help.
